name: Automation
on:
  push:
    branches: ['**']
  release:
    types: [published]
  pull_request:
    branches: ['**']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci

      - name: Test Types
        run: npm run types

      - name: Build for Distribution
        run: xvfb-run --auto-servernum npm run build

      - name: Upload chrome extension
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: upload
          path: .upload/

      # Automatically attach files to release
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: .upload/*
